//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 07:38:38 PM MESZ 
//


package at.jku.smartshopper.objects;

import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <p>Java class for basket complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="basket">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rows" type="{http://backend.smartshopper.jku.at/}basketRow" maxOccurs="unbounded"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shopId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Basket {

	@JsonProperty("rows")
    protected List<BasketRow> rows;
	@JsonProperty("userId")
    protected String userId;
	@JsonProperty("shopId")
    protected long shopId;
	
	public Basket() {
		super();
	}
	
	public Basket(List<BasketRow> rows, String userId, long shopId) {
		super();
		this.rows =  rows;
		this.userId = userId;
		this.shopId = shopId;
	}

    /**
     * Gets the value of the rows property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rows property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRows().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasketRow }
     * 
     * 
     */
    public List<BasketRow> getRows() {
        if (rows == null) {
            rows = new ArrayList<BasketRow>();
        }
        return this.rows;
    }

    public void setRows(List<BasketRow> rows) {
		this.rows = rows;
	}

	/**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the shopId property.
     * 
     */
    public long getShopId() {
        return shopId;
    }

    /**
     * Sets the value of the shopId property.
     * 
     */
    public void setShopId(long value) {
        this.shopId = value;
    }

}
